/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_zf_myapplication_bspatch_Bspatch */

#ifndef _Included_com_zf_myapplication_bspatch_Bspatch
#define _Included_com_zf_myapplication_bspatch_Bspatch
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_zf_myapplication_bspatch_Bspatch
 * Method:    bsPatch
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_zf_myapplication_bspatch_Bspatch_bsPatch
  (JNIEnv *, jclass, jstring, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
